### ISSUE TITLE
Respect input::placeholder:after css selector in IE9

### ISSUE THREAD

**Issue by focused** [jamesallardice/Placeholders.js#94]
I want to colorize the last letter of placeholders for required fields, `after` works in modern browsers, but not with the polyfill in IE9.

``` html
<input type-"text" value="" placeholder="name" />
```

``` css
input::placeholder:after {
  color: red;
  content: "*";
  opacity: 1;
}
```
